development:
  adapter: mysql
  database: rewiredstate_development
  username: root
  password: 

production:
  adapter: mysql
  database: rewiredstate_production
  username: root
  password: 

staging:
  adapter: mysql
  database: rewiredstate_staging
  username: root
  password: 

test:
  adapter: mysql
  database: rewiredstate_test
  username: root
  password: 

